# This workflow will lint, unit test, and integration test simbak.

name: Python test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest flake8
          python -m pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 simbak/ tests/
      - name: Unit test
        run: |
          python -m pytest tests/unit/
      - name: Integration test
        run: |
          python -m pytest tests/integ/
